AWSTemplateFormatVersion: 2010-09-09

Description: This CloudFormation template will create the Glue.

# The Metadata field serves to make the parameters user-friendly.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Name"
        Parameters:
          - GlueService
      -
        Label:
          default: "Glue - Network Configuration"
        Parameters:
          - VpcID
          - SubnetId
          - SecurityGroup
      -
        Label:
          default: "Glue - Database Inbound Connection"
        Parameters:
          - JDBCString
          - JDBCUser
          - JDBCPassword
      -  
        Label:
          default: "RDS - Network Configuration"
        Parameters:
          - VpcID
          - SubnetIDRDS
          - SecurityGroupRDS 
      -
        Label:
          default: "RDS - Outbound Connection" 
        Parameters:
          - RDS
          - RDSName
          - EngineVersion
          - MasterUserPassword   
        
    ParameterLabels:
      GlueService:
        default: "Enter your Glue's name"
      VpcID:
        default: "VPC"
      SubnetId:
        default: "Subnet"
      SecurityGroup:
        default: "SecurityGroup"
      JDBCString:
        default: "Database connection string"
      JDBCUser:
        default: "Database User"
      JDBCPassword:
        default: "Database Password"
      RDSName:
        default: "Name for your RDS"
      EngineVersion:
        default: "EngineVersion"
      MasterUserPassword:
        default: "MasterUserPassword"
      VpcIDRDS:
        default: "VPC for RDS"
      SubnetIDRDS:
        default: "Subnet for RDS" 
      SecurityGroupRDS:
        default: "Security Group for RDS"    

Parameters:
  GlueService:
    Type: String

  VpcID:
    Description: "Choose the VPC"
    Type: AWS::EC2::VPC::Id
  
  SecurityGroup:
    Description: 'Choose the Security Group'
    Type: AWS::EC2::SecurityGroup::Id
  
  SubnetId:
    Description: 'Choose the Subnet ID'
    Type: String
  
  JDBCString:  
    Description: 'Enter the JDBC String'
    Type: String
    Default: 'jdbc:protocol://host:port/databasename'
  
  JDBCUser:  
    Description: 'Enter the Database user'
    Type: String
  
  JDBCPassword:  
    Description: 'Enter the Database Password'
    Type: String

  SubnetIDRDS:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Select the subnets to associate with the VPC endpoint, choose at least 2 subnets.'

  EngineVersion:
    Description: 'What is your MySQL engine version?'
    Type: String
    AllowedValues: [5.6, 5.7, 8.0]
 
  MasterUserPassword:
    Description: "Write down what your RDS admin password will be."
    Type: String

  RDSName:
    Type: String

Resources:

# Creation of permission role for services.  
  
  IAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: !Ref GlueService
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

# Database, Connections and Crawler are the components for creating Glue.

  Database:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Ref GlueService
      CatalogId: !Ref AWS::AccountId

  Connections:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId 
      ConnectionInput: 
        ConnectionType: 'JDBC'
        PhysicalConnectionRequirements:
          SecurityGroupIdList: 
            - !Ref SecurityGroup
          SubnetId: !Ref SubnetId 
        ConnectionProperties: {
          'JDBC_CONNECTION_URL': !Ref JDBCString,
          'USERNAME': !Ref JDBCUser,
          'PASSWORD': !Ref JDBCPassword,
          'JDBC_ENFORCE_SSL': false
        }
        Name: !Ref GlueService
 
  Crawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref GlueService
      Role: !GetAtt IAM.Arn
      DatabaseName: !Ref Database
      Targets:
        JdbcTargets:
          - ConnectionName: !Ref GlueService
            Path: !Join [ "", [!GetAtt RDSAuroraServerless.Endpoint.Address, ":", "3306", /, !Ref RDSName] ]

#  Crawler2:
#    Type: AWS::Glue::Crawler
#    Condition: NotCreationRDS
#    Properties:
#      Name: !Ref GlueService
#      Role: !GetAtt IAM.Arn
#      DatabaseName: !Ref Database
#      Targets:
#        JdbcTargets:
#          - ConnectionName: !Ref GlueService
#            Path: !Ref JDBC

# Creation or not RDS.

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
       DBSubnetGroupDescription: !Ref RDSName
       SubnetIds: !Ref SubnetIDRDS
  
  RDSAuroraServerless:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref RDSName
      MasterUsername: admin
      MasterUserPassword: !Ref MasterUserPassword
      DBClusterIdentifier: !Ref RDSName
      ScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 2
        SecondsUntilAutoPause: 300
      BackupRetentionPeriod: 7
      DeletionProtection: false
      VpcSecurityGroupIds:
        - !Ref SecurityGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup