AWSTemplateFormatVersion: 2010-09-09  
  
Resources:

  SecretsManagerHanaDev:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "HANA-ACCESS-DEV"
      Description: "Secret for Hana Enviroment DEV"
      SecretString: '{"API_DATABASE_CONNECTION_STRING":"hana://MVNHR:TecNhrDc243@10.63.3.198:30056"}'

  SecretsManagerHanaQA:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "HANA-ACCESS-QA"
      Description: "Secret for Hana Enviroment QA"
      SecretString: '{"API_DATABASE_CONNECTION_STRING":"hana://MVNHR:TecNhrDc243@10.63.3.198:30056"}'

  SecretsManagerHanaProd:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "HANA-ACCESS-PRD"
      Description: "Secret for Hana Enviroment PROD"
      SecretString: '{"API_DATABASE_CONNECTION_STRING":"hana://MVNHR:TecNhrDc243@10.63.3.198:30056"}'
  
  SecretsManagerRDSDev:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "RDS-ACCESS-DEV"
      Description: "Secret for RDS Enviroment DEV"
      SecretString: '{"API_DATABASE_CONNECTION_STRING":"mssql%2Bpyodbc://userradtqa:TwCr4tqTP44Y%5Cq%7C%2BaCa0@brdatamodel-qa.c7xozptlcsmw.eu-central-1.rds.amazonaws.com:1433/RA_CS_DataModel?driver=ODBC%2BDriver%2B17%2Bfor%2BSQL%2BServer"}'

  SecretsManagerRDSQA:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "RDS-ACCESS-QA"
      Description: "Secret for RDS Enviroment QA"
      SecretString: '{"API_DATABASE_CONNECTION_STRING":"mssql%2Bpyodbc://userradtqa:TwCr4tqTP44Y%5Cq%7C%2BaCa0@brdatamodel-qa.c7xozptlcsmw.eu-central-1.rds.amazonaws.com:1433/RA_CS_DataModel?driver=ODBC%2BDriver%2B17%2Bfor%2BSQL%2BServer"}'

  SecretsManagerRDSProd:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "RDS-ACCESS-PRD"
      Description: "Secret for RDS Enviroment PRD"
      SecretString: '{"API_DATABASE_CONNECTION_STRING":"mssql%2Bpyodbc://userradtqa:TwCr4tqTP44Y%5Cq%7C%2BaCa0@brdatamodel-qa.c7xozptlcsmw.eu-central-1.rds.amazonaws.com:1433/RA_CS_DataModel?driver=ODBC%2BDriver%2B17%2Bfor%2BSQL%2BServer"}'

  SecretsManagerConfigurationHana:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "BASIC-CONFIGURATION-SALES"
      Description: "Secret for Hana Configuration"
      SecretString: '{"API_ENVIRONMENT":"production","API_PORT":"80","API_SCHEMA":"http"}'