AWSTemplateFormatVersion: 2010-09-09

Description: This CloudFormation template will create the API Gateway, Lambda, Glue and Athena.

# The Metadata field serves to make the parameters user-friendly.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Name of Resources"
        Parameters:
          - Name
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - SubnetIds
          - SecurityGroupId
      -
        Label:
          default: "API Gateway"
        Parameters:
          - CreationVCPEndpointExecuteAPI
          - IDVPCEndpoint
          - ResourcePolicy
      -
        Label:
          default: "Lambda"
        Parameters: 
          - LambdaRuntime
          - NameofBucketApplication
          - NameofFileApplication
      -
        Label:
          default: "Glue"
        Parameters:
          - CreationVCPEndpointExecuteS3
          - RouteTable
      -
        Label:
          default: "Athena - Inbound data from S3"
        Parameters:
          - InboundS3
      -
        Label:
          default: "Athena - Outputting data to S3"
        Parameters:
          - BucketS3
          - NameBucketS3
          - S3URI      

    ParameterLabels:
      Name:
        default: "Name"      
      VpcId:
        default: "VPC"
      SubnetIds:
        default: "Subnet"
      SecurityGroupId:
        default: "Security Group"
      LambdaRuntime:
        default: "Lambda - Runtime"
      NameofBucketApplication:
        default: "Bucket"
      NameofFileApplication:
        default: "File"
      CreationVCPEndpointExecuteAPI:
        default: "VPCE for your API Gateway"
      CreationVCPEndpointExecuteS3:
        default: "VPCE for your S3 Gateway"
      IDVPCEndpoint:
        default: "VPC Endpoint"
      ResourcePolicy:
        default: "VPC Resource Policy"
      BucketS3:
        default: "Do you want to create an S3 bucket?"
      NameBucketS3:
        default: "If yes, create a unique name for Bucket S3"
      NameDataSource:
        default: "Input the name of the data source"
      S3URI:
        default: "Input S3 URI"
      RouteTable: 
        default: "Route Table for VPCE S3 Gateway"
      InboundS3:
        default: "Input S3 URI"
      
# The Parameters block is the sector where the user places the variables.

Parameters:

  Name:
    Description: "This will be the name of your API Gateway, Lambda, Glue and Athena. First character must be a letter. Can't contain two consecutive hyphens. Can't end with a hyphen."
    Type: String

  LambdaRuntime:
    Type: String
    Description: 'What is your application runtime?'
    AllowedValues: [nodejs14.x, nodejs12.x, nodejs10.x, python3.9, python3.8, python3.7, python3.6, python2.7, ruby2.7, ruby2.5, java11, java8.al2, java8, go1.x, dotnetcore3.1, dotnetcore2.1, provided.al2, provided]

  NameofBucketApplication:
    Type: String
    Description: 'Which bucket is your function in?'

  NameofFileApplication:
    Type: String
    Description: "Enter your function's .zip file."

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'Select the VPC ID for the VPC endpoint.' 

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Select the subnets to associate with the VPC endpoint.'

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: 'Select security group to associate with the VPC endpoint.'

  CreationVCPEndpointExecuteAPI:
    Type: String
    AllowedValues: [true, false]
    Description: 'If you want to create a VPC Endpoint Execute API choose true, if not choose false.'

  CreationVCPEndpointExecuteS3:
    Type: String
    AllowedValues: [true, false]
    Description: 'If you want to create a VPC Endpoint S3 Gateway choose true, if not choose false.'

  IDVPCEndpoint:
    Type: String
    Description: 'Write the VPCE only if you checked the option sign as false. To learn more about what a VPC Endpoint is, go to: https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html'

  ResourcePolicy:
    Type: String
    Description: 'Input the VPC Endpoint of your origin, Sensedia=vpce-07516d43e5467b5f9'
    Default: 'vpce-07516d43e5467b5f9'

  BucketS3:
    Type: String
    AllowedValues: [true, false]
    Description: 'If you want to create an S3 bucket choose true, if not choose false.'

  NameBucketS3:
    Type: String
    Description: 'Write the name of Bucket S3 only if you checked the option sign as true. To learn more about Bucket S3 naming rules, visit: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html'
    AllowedPattern: ^[a-zA-Z0-9\-\.]*$
    ConstraintDescription: "Bucket names can consist only of lowercase letters, numbers, dots (.), hyphens (-) and must begin and end with a letter or number."

  S3URI:
    Type: String
    Description: 'If false, input the S3 URI, example: s3://bucket/.'

  RouteTable:
    Type: String
    Description: 'Only write the Route Table if the option above is yes, if you want to know more about Route Tables, visit the link: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html'

  InboundS3:
    Type: String
    Description: The bucket must contain the files that Athena will query, input the bucket address, eg s3://bucket/

# Conditions are the decision parameters of the template.

Conditions:
  CreationVCPEndpointExecuteAPI: !Equals [!Ref CreationVCPEndpointExecuteAPI, true]
  CreationVCPEndpointS3: !Equals [!Ref CreationVCPEndpointExecuteS3, true]
  CreationS3Bucket: !Equals [!Ref BucketS3, true]

Resources:

  GlueIAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: !Sub ${Name}-gluepolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

# LambdaIAM (permission) and LambdaFunction are part of the creation of Lambda.

  LambdaIAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: !Sub ${Name}-lambdapolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref Name
      Runtime: !Ref LambdaRuntime
      Code:
        S3Bucket: !Ref NameofBucketApplication
        S3Key: !Ref NameofFileApplication
      Handler: python_test.lambda_handler
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt 
        - LambdaIAM
        - Arn

# Creation of VPC Endpoint.

  VPCEndpointExecuteAPI:
    Type: AWS::EC2::VPCEndpoint
    Condition: CreationVCPEndpointExecuteAPI
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .execute-api
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId
      SubnetIds: 
        Ref: SubnetIds
      VpcEndpointType: Interface
      VpcId: 
        Ref: VpcId

  VPCEndpointS3Gateway:
    Type: AWS::EC2::VPCEndpoint
    Condition: CreationVCPEndpointS3
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .s3
      VpcEndpointType: Gateway
      VpcId: 
        Ref: VpcId
      RouteTableIds:
        - !Ref RouteTable

# APIGateway, APIGatewayResource, APIGatewayDeploy, APIGatewayStage, APIGatewayMethod are the components to create the API Gateway.

  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref Name
      EndpointConfiguration:
        Types:
          - PRIVATE
        VpcEndpointIds:
          - !If [CreationVCPEndpointExecuteAPI, !Ref VPCEndpointExecuteAPI, !Ref IDVPCEndpoint]      
      Policy:
        Statement:
          - Action: 'execute-api:Invoke'
            Effect: Allow
            Principal: '*'
            Resource: 'execute-api:/*'
          - Action: 'execute-api:Invoke'
            Condition:
              StringNotEquals:
                'aws:SourceVpce': !Ref ResourcePolicy
            Effect: Deny
            Principal: '*'
            Resource: 'execute-api:/*'
        Version: 2012-10-17

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt 
        - APIGateway
        - RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref APIGateway

  APIGatewayDeploy:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref APIGateway
    DependsOn:
      - APIGatewayMethod
      - ApiGatewayResource

  APIGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref APIGateway
      DeploymentId: !Ref APIGatewayDeploy
      StageName: dev

# LambdaPermission is the policy that connects Function with API Gateway.

  LambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - LambdaFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref APIGateway
          - /*/*/*

  APIGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref APIGateway
      AuthorizationType: NONE       
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }
      Integration:
        IntegrationResponses:        
          - StatusCode: 200 
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - LambdaFunction
              - Arn
            - /invocations

# S3 bucket creation.

  S3:
    Type: AWS::S3::Bucket
    Condition: CreationS3Bucket
    Properties:
      BucketName: !If [CreationS3Bucket, !Ref NameBucketS3, !Ref AWS::NoValue]  

# Creation of Glue database and crawler.

  Database:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Ref Name
      CatalogId: !Ref AWS::AccountId

  Crawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref Name
      Role: !GetAtt GlueIAM.Arn
      DatabaseName: !Ref Database
      Targets:
        S3Targets:
          - Path: !Ref InboundS3 

# Creating data output for Athena.

  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Ref Name
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !If [CreationS3Bucket, !Join ["", [s3://, !Ref S3]], !Ref S3URI]